# Generated by Django 5.0 on 2023-12-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thread Name')),
                ('user_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_one_threads', to=settings.AUTH_USER_MODEL, verbose_name='User One')),
                ('user_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_two_threads', to=settings.AUTH_USER_MODEL, verbose_name='User Two')),
            ],
            options={
                'verbose_name': 'Chat Thread',
                'verbose_name_plural': 'Chat Threads',
                'unique_together': {('user_one', 'user_two')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('sent_time_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time and date')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickrchat.chatthread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
            },
        ),
    ]
