# Generated by Django 5.0 on 2023-12-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0002_chatmessage_sent_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sent_time_date',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sent_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Time'),
        ),
    ]
