# Generated by Django 5.0 on 2023-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0004_rename_sent_time_chatmessage_sent_time_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_time_12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Time-12'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_time_24',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Time-24'),
        ),
    ]
