# Generated by Django 5.0 on 2023-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0005_alter_chatmessage_sent_time_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='Image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='', verbose_name='File'),
        ),
    ]
