# Generated by Django 5.0 on 2023-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0006_chatmessage_image_chatmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='Image',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=1000, null=True, upload_to='', verbose_name='File'),
        ),
    ]
