# Generated by Django 5.0 on 2023-12-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0007_alter_chatmessage_image_alter_chatmessage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='Image',
            new_name='image',
        ),
    ]
