# Generated by Django 5.0 on 2023-12-16 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0008_rename_image_chatmessage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thread Name')),
                ('thread_avatar', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='', verbose_name='Avatar Image')),
                ('users', models.ManyToManyField(related_name='chat_threads', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Group Chat Thread',
                'verbose_name_plural': 'Group Chat Threads',
            },
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('file', models.FileField(blank=True, default=None, max_length=1000, null=True, upload_to='', verbose_name='File')),
                ('image', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='', verbose_name='Image')),
                ('sent_time_12', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time-12')),
                ('sent_time_24', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time-24')),
                ('sent_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickrchat.groupchatthread', verbose_name='Group Thread')),
            ],
            options={
                'verbose_name': 'Group Chat Message',
                'verbose_name_plural': 'Group Chat Messages',
            },
        ),
    ]
