# Generated by Django 5.0 on 2023-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0009_groupchatthread_groupchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatthread',
            name='groupuniqueid',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
