# Generated by Django 5.0 on 2023-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0010_groupchatthread_groupuniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatthread',
            name='groupuniqueid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
