# Generated by Django 5.0 on 2023-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickrchat', '0014_groupchatthread_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatthread',
            name='thread_avatar',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='images/', verbose_name='Avatar Image'),
        ),
    ]
