# Generated by Django 5.0 on 2023-12-15 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuserml', '0003_alter_user_blocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocklist',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Blocked List'),
        ),
    ]
