# Generated by Django 5.0 on 2023-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuserml', '0004_alter_user_blocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Email Token'),
        ),
    ]
