# Generated by Django 5.0 on 2023-12-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuserml', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='Is Updated'),
        ),
    ]
